version: "3"
services:
  api-database:
    image: mongo:latest
    container_name: "api-database"
    ports:
      - 27017:27017
    command: --serviceExecutor adaptive
    # command: --smallfiles
  api:
    image: webshop-api-shopping-docker-image
    ports:
      - 8083:8083
    links:
      - api-database